dist: trusty
language: python

python:
  - "3.6"

install:
  - pip install -U numpy flake8 pytest
  - python setup.py install

script:
  - flake8 --show-source .
  - pytest

notifications:
  email: false
